### PR TITLE
[WIP]Add basic styling

### PR DESCRIPTION
**Pull request by Caleb9193**
Adds basic styling to background of home page. Deleted all default styling from App.css and created styling in index.css

Example so far
screen shot 2016-10-28 at 11 51 39 am

### CODE REVIEW

**Comment by rrgayhart** [comment]
@Caleb9193 - For a styling change, it's really helpful to include images of the page in the PR description. Bonus points for using something like recordit to capture a gif of using the site (if relevant)

**Comment by matthewrpacker** [comment]
@Caleb9193 It looks like a clean refactor.  I like that you have the image locally and specify the file path rather than a url.  I don't have much else to add.  Nice work!

**Comment by dtinianow** [comment]
@Caleb9193 My only feedback is to make sure you use a font other than black once you start adding more content to the page to make sure the text is visible.  Like Matt, I also like that you pull the image from a local file.  This will help ensure consistency for your photo.  Nice start to your project, looking forward to seeing how it turns out.

**Comment by twhitinger** [comment]
@Caleb9193 Hi Caleb, I think from a styling perspective we should look at wireframing the layout we want for the dashboard/user summary screen. How we want to display the summary of the users uploaded videos. Maybe we can take some inspiration from some modern themes on the bootstrap website and see how we can create them custom using react. http://themes.getbootstrap.com/products/application.

**Pull request merged**
